name: CI on Push to Main

on:
  push:
    branches:
      - main

jobs:
  static-test:
	  name: Run CI
	  runs-on: ubuntu-latest

	  steps:
	    - uses: actions/checkout@v4
	      with:
		    fetch-depth: 1
	    - uses: dominikh/staticcheck-action@v1.2.0
	      with:
		    version: "2022.1.1"

  unit-test:
    name: Run Unit Tests
    needs: static-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test unit_test.go

  integration-test:
    name: Run Integration Tests
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test main_test.go

  build:
    name: Build Docker Image
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag math-services:$(date +%s)
