name: CI on Push to Main

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.23"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}

  unit-test:
    name: Run Unit Tests
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test unit_test.go

  integration-test:
    name: Run Integration Tests
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test main_test.go

  build:
    name: Build Docker Image
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag math-services:$(date +%s)
