name: Unit Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test unit_test.go

  integration-test:
    name: Run Integration Tests
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test main_test.go
